# Generated by Django 6.0.1 on 2026-01-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], max_length=10),
        ),
    ]
