# Generated by Django 6.0.1 on 2026-01-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_slot_patient_alter_slot_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
